export const plants = [
    {
        id: 0,
        name: 'Aloe Vera',
        image: 'https://www.almanac.com/sites/default/files/styles/or/public/image_nodes/aloe-vera-white-pot_sunwand24-ss_edit_0.jpg?itok=uOJaHAeR',
        sunlight: 'Direct Sunlight',
        value: 0,
    },
    {
        id: 1,
        name: 'Snake Plant',
        image: 'https://www.almanac.com/sites/default/files/styles/or/public/image_nodes/shutterstock_679786570.jpg?itok=D3_VPPOU',
        sunlight: 'Indirect Sunlight',
        value: 0,
    },
    {
        id: 2,
        name: 'Spider Plant',
        image: '',
        sunlight: 'Indirect Sunlight',
        value: 0,
    },
    {
        id: 3,
        name: 'Peace Lily',
        image: '',
        sunlight: 'Indirect Sunlight',
        value: 0,
    },
    {
        id: 4,
        name: 'Rubber Plant',
        image: '',
        sunlight: 'Indirect Sunlight',
        value: 0,
    },
    {
        id: 5,
        name: 'Pothos',
        image: 'https://www.almanac.com/sites/default/files/image_nodes/pothos.jpg',
        sunlight: 'Indirect Sunlight',
        value: 0,
    },
    {
        id: 6,
        name: 'Parlor Palm',
        image: '',
        sunlight: 'Indirect Sunlight',
        value: 0,
    },
    {
        id: 7,
        name: 'Boston Fern',
        image: '',
        sunlight: 'Indirect Sunlight',
        value: 0,
    },
    {
        id: 8,
        name: 'ZZ Plant',
        image: '',
        sunlight: 'Indirect Sunlight',
        value: 0,
    },
    {
        id: 9,
        name: 'Jade Plant',
        image: '',
        sunlight: 'Direct Sunlight',
        value: 0,
    },
    {
        id: 10,
        name: 'African Violet',
        image: '',
        sunlight: 'Indirect Sunlight',
        value: 0,
    },
    {
        id: 11,
        name: 'Fiddle Leaf Fig',
        image: '',
        sunlight: 'Direct Sunlight',
        value: 0,
    },
    {
        id: 12,
        name: 'Potato Plant',
        image: '',
        sunlight: 'Direct Sunlight',
        value: 0,
    }
];